
[build]
  publish = "public"  # Ganti dengan folder yang berisiasdsadasd ftasdsarersis
  functions = "netlify/functions"  # Folder untk dsxcczxcxzc



[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"  # Mengarahkan request ke functio
  status = 200
