
[build]
  publish = "public"  # Ganti dengan folder yang berisiasdsadasdftasdsarersis
  functions = "netlify/functions"  # Folder untk dsxcczxc



[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"  # Mengarahkan request ke functio
  status = 200
