[build]
  publish = "public"  # Ganti dengan folder yang berisi file statis
  functions = "netlify/functions"  # Folder untk sdaasd

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"  # Mengarahkan request ke functio
  status = 200
