[build]
  publish = "public"  # Ganti dengan folder yang berisi file statis
  functions = "netlify/functions"  # Folder untuk e 

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"  # Mengarahkan request ke function
  status = 200
